/* =========================================================
   LE GOURMET — DATABASE SCHEMA (MySQL 8+, UTF8MB4)
   ---------------------------------------------------------
   - Creates database `restaurant`
   - Tables: admins, dishes
   - Indexes for performance
   - Demo admin (email: admin@example.com / pass: admin123)
   - A few sample menu items
   ========================================================= */

-- 0) Create database (safe to run multiple times)
CREATE DATABASE IF NOT EXISTS restaurant
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE restaurant;

-- 1) Drop tables if you really want a clean reset (optional)
-- DROP TABLE IF EXISTS dishes;
-- DROP TABLE IF EXISTS admins;

-- 2) Admins table: simple email + password hash
CREATE TABLE IF NOT EXISTS admins (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  email          VARCHAR(190) NOT NULL UNIQUE,
  password_hash  VARCHAR(255) NOT NULL,
  created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3) Dishes table: menu items used by the public site + admin dashboard
CREATE TABLE IF NOT EXISTS dishes (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  nom          VARCHAR(150) NOT NULL,
  description  TEXT NULL,
  prix         DECIMAL(10,2) NOT NULL DEFAULT 0,
  categorie    ENUM('Entrée','Plat','Dessert','Boisson') NOT NULL,
  image_url    VARCHAR(500) NULL,
  created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_dishes_categorie (categorie),
  INDEX idx_dishes_nom (nom)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4) Seed admin (password = admin123)
--    This is a bcrypt hash generated by password_hash('admin123', PASSWORD_BCRYPT)
INSERT INTO admins (email, password_hash)
VALUES
  ('admin@example.com', '$2y$10$8vYh3k1yW7c0i9wTtZ3QX.WsY0i6z6vK7F9d2mQz6aKqQf0XCPbH6')
ON DUPLICATE KEY UPDATE email = VALUES(email);

-- 5) Sample dishes (you can delete/change later in the dashboard)
INSERT INTO dishes (nom, description, prix, categorie, image_url) VALUES
  ('Foie Gras Poêlé', 'Foie gras, chutney de figues, brioche', 28.50, 'Entrée',
   'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80'),
  ('Bœuf de Charolais', 'Côte de bœuf grillée, légumes de saison', 32.00, 'Plat',
   'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=900&q=80'),
  ('Tarte Tatin', 'Aux pommes, glace vanille', 12.00, 'Dessert',
   'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=900&q=80'),
  ('Champagne Brut', 'Cuvée spéciale', 12.00, 'Boisson',
   'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=900&q=80');

-- 6) Quick sanity checks (optional)
-- SELECT * FROM admins;
-- SELECT id, nom, prix, categorie FROM dishes ORDER BY categorie, nom;
